### ISSUE TITLE
Issue when persisting using oneToMany annotation in relmongo

### ISSUE THREAD

**Issue by suraj-mandal** [kaiso/relmongo#103]
While performing a sample test of relmongo in my project I am facing the given issue:
```
java.lang.RuntimeException: java.lang.NoSuchMethodError: com.krakken.learningmongo.models.Person$$EnhancerByCGLIB$$af5ebd31: method 'void <init>()' not found

	at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:281)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:170)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:158)
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:516)
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:285)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:628)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:168)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.mongodb.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:158)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:220)
	at jdk.proxy2/jdk.proxy2.$Proxy114.findById(Unknown Source)
	at com.krakken.learningmongo.repository.PersonRepositoryTests.testOneToManyMappingBetweenCarAndPerson(PersonRepositoryTests.java:71)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.NoSuchMethodError: com.krakken.learningmongo.models.Person$$EnhancerByCGLIB$$af5ebd31: method 'void <init>()' not found
	at com.krakken.learningmongo.models.Person$$EnhancerByCGLIB$$af5ebd31.newInstance(<generated>)
	at io.github.kaiso.relmongo.mongo.PersistentRelationResolver.lazyLoader(PersistentRelationResolver.java:55)
	at io.github.kaiso.relmongo.events.callback.PersistentPropertyPostLoadingCallback.doWith(PersistentPropertyPostLoadingCallback.java:103)
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:728)
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:707)
	at io.github.kaiso.relmongo.events.processor.RelMongoProcessor.onAfterConvert(RelMongoProcessor.java:127)
	at io.github.kaiso.relmongo.events.processor.RelMongoProcessor.onApplicationEvent(RelMongoProcessor.java:86)
	at io.github.kaiso.relmongo.config.RelMongoBeanPostProcessor$RelMongoEventPublisher.publishEvent(RelMongoBeanPostProcessor.java:84)
	at org.springframework.data.mongodb.core.EntityLifecycleEventDelegate.publishEvent(EntityLifecycleEventDelegate.java:53)
	at org.springframework.data.mongodb.core.MongoTemplate.maybeEmitEvent(MongoTemplate.java:2363)
	at org.springframework.data.mongodb.core.MongoTemplate$ReadDocumentCallback.doWith(MongoTemplate.java:3284)
	at org.springframework.data.mongodb.core.MongoTemplate.executeFindOneInternal(MongoTemplate.java:2874)
	at org.springframework.data.mongodb.core.MongoTemplate.doFindOne(MongoTemplate.java:2536)
	at org.springframework.data.mongodb.core.MongoTemplate.findOne(MongoTemplate.java:817)
	at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.findById(SimpleMongoRepository.java:127)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:277)
	... 21 more

```

Here are my models

**Car.java**

```java
package com.krakken.learningmongo.models;

import io.github.kaiso.relmongo.annotation.ManyToOne;
import lombok.Builder;
import lombok.Data;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "car")
@Data
public class Car {

    @Id
    private String id;

    @Indexed(unique = true)
    private int identifier;

    public Car(int identifier) {
        this.identifier = identifier;
    }

    private String manufacturer;
    private Color color;

    @ManyToOne(mappedBy = "cars")
    private Person Owner;
}

```

**Person.java**

```java
package com.krakken.learningmongo.models;

import io.github.kaiso.relmongo.annotation.CascadeType;
import io.github.kaiso.relmongo.annotation.FetchType;
import io.github.kaiso.relmongo.annotation.JoinProperty;
import io.github.kaiso.relmongo.annotation.OneToMany;
import lombok.*;

import org.bson.types.ObjectId;
import org.springframework.data.mongodb.core.mapping.Document;


import java.util.List;


@Document(collection = "person")
@Data
@Builder
public class Person {

    private ObjectId id;
    private String name;
    private String email;


    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @JoinProperty(name = "carsrefs")
    @Singular
    private List<Car> cars;
}

```

and I have added the relMongo annotation like this,
```java
package com.krakken.learningmongo;

import io.github.kaiso.relmongo.config.EnableRelMongo;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.data.mongodb.config.EnableMongoAuditing;
import org.springframework.data.mongodb.repository.config.EnableMongoRepositories;

@SpringBootApplication
@EnableRelMongo(mongoTemplateRef = "mongoTemplate")
@EnableMongoAuditing
public class LearningMongoApplication {

    public static void main(String[] args) {
        SpringApplication.run(LearningMongoApplication.class, args);
    }

}

```

While performing the given series of test, I am facing the above issue.
```java
package com.krakken.learningmongo.repository;


import com.krakken.learningmongo.config.MongoSpringConfiguration;
import com.krakken.learningmongo.models.Account;
import com.krakken.learningmongo.models.Car;
import com.krakken.learningmongo.models.Color;
import com.krakken.learningmongo.models.Person;
import com.mongodb.MongoConfigurationException;
import io.github.kaiso.relmongo.util.RelMongoConstants;
import org.bson.Document;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.data.mongo.DataMongoTest;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.data.mongodb.core.MongoOperations;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;


import java.util.Arrays;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;


@ActiveProfiles("test")
@ExtendWith(SpringExtension.class)
@SpringBootTest
public class PersonRepositoryTests {

    @Autowired
    private PersonRepository personRepository;

    @Autowired
    private CarRepository carRepository;

    @Autowired
    private MongoOperations mongoOperations;

    @BeforeEach
    void clearDatabase() {
        personRepository.deleteAll();
        carRepository.deleteAll();
    }

    @Test
    @DisplayName("Test one to many mapping between car and persons")
    void testOneToManyMappingBetweenCarAndPerson() {
        Car car1 = new Car(1);
        car1.setColor(Color.BLUE);
        car1.setManufacturer("BMW");
        Car car2 = new Car(2);
        car2.setColor(Color.RED);
        car2.setManufacturer("BMW");

        car1 = carRepository.save(car1);
        car2 = carRepository.save(car2);

        Person person = Person.builder()
                .name("Dave")
                .email("dave@email.com")
                .cars(Arrays.asList(new Car[]{car1, car2}))
                .build();
        person = personRepository.save(person);

        Optional<Car> foundCarOptional = carRepository.findById(car1.getId());
        assertTrue(foundCarOptional.isPresent());

        Car foundCar = foundCarOptional.get();

        assertNotNull(foundCar.getOwner());
        assertEquals(foundCar.getOwner().getId(), person.getId());

        Optional<Person> foundPersonOptional = personRepository.findById(person.getId().toString());
        assertTrue(foundPersonOptional.isPresent());

        Person foundPerson = foundPersonOptional.get();

        assertEquals(2, foundPerson.getCars().size());

    }
}

```

Can you tell me which changes I have to make in order to make it work?

I am in ubuntu 23.04.

**Comment by kaiso** [comment]
Hello @suraj-mandal  it should because of the spring version, please see the compatiblity matrix in the wiki
