### ISSUE TITLE
Can't create relation with `Long` identifier

### ISSUE THREAD

**Issue by sgornostal** [kaiso/relmongo#38]
I'm trying to create relation with `Long` id. Application throws next exception:

```
java.lang.ClassCastException: class java.lang.Long cannot be cast to class org.bson.types.ObjectId (java.lang.Long is in module java.base of loader 'bootstrap'; org.bson.types.ObjectId is in unnamed module of loader 'app')
	at org.bson.Document.getObjectId(Document.java:249)
	at io.github.kaiso.relmongo.mongo.DocumentUtils.mapIdentifier(DocumentUtils.java:63)
	at io.github.kaiso.relmongo.mongo.PersistentRelationResolver.resolveOnLoading(PersistentRelationResolver.java:56)
	at io.github.kaiso.relmongo.events.processor.RelMongoProcessor.onAfterLoad(RelMongoProcessor.java:57)
	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:56)
	at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:31)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354)
	at org.springframework.data.mongodb.core.ReactiveMongoTemplate.maybeEmitEvent(ReactiveMongoTemplate.java:2009)
	at org.springframework.data.mongodb.core.ReactiveMongoTemplate$ProjectingReadCallback.doWith(ReactiveMongoTemplate.java:2588)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	at com.mongodb.reactivestreams.client.internal.ObservableToPublisher$1.onNext(ObservableToPublisher.java:68)
	at com.mongodb.async.client.AbstractSubscription.onNext(AbstractSubscription.java:135)
	at com.mongodb.async.client.AbstractSubscription.processResultsQueue(AbstractSubscription.java:203)
	at com.mongodb.async.client.AbstractSubscription.tryProcessResultsQueue(AbstractSubscription.java:159)
	at com.mongodb.async.client.AbstractSubscription.addToQueue(AbstractSubscription.java:117)
	at com.mongodb.async.client.MongoIterableSubscription$2.onResult(MongoIterableSubscription.java:101)
	at com.mongodb.async.client.MongoIterableSubscription$2.onResult(MongoIterableSubscription.java:87)
	at com.mongodb.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:135)
	at com.mongodb.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:99)
	at com.mongodb.async.client.MongoIterableSubscription.requestMoreData(MongoIterableSubscription.java:87)
	at com.mongodb.async.client.MongoIterableSubscription$1.onResult(MongoIterableSubscription.java:55)
	at com.mongodb.async.client.MongoIterableSubscription$1.onResult(MongoIterableSubscription.java:48)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.async.client.AsyncOperationExecutorImpl$1$1.onResult(AsyncOperationExecutorImpl.java:70)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.operation.FindOperation$3.onResult(FindOperation.java:822)
	at com.mongodb.operation.OperationHelper$ReferenceCountedReleasingWrappedCallback.onResult(OperationHelper.java:353)
	at com.mongodb.operation.CommandOperationHelper$1.onResult(CommandOperationHelper.java:389)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor$2.onResult(DefaultServer.java:207)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.connection.CommandProtocolImpl$1.onResult(CommandProtocolImpl.java:102)
	at com.mongodb.connection.DefaultConnectionPool$PooledConnection$1.onResult(DefaultConnectionPool.java:458)
	at com.mongodb.connection.UsageTrackingInternalConnection$2.onResult(UsageTrackingInternalConnection.java:110)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:381)
	at com.mongodb.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:359)
	at com.mongodb.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:651)
	at com.mongodb.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:618)
	at com.mongodb.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:487)
	at com.mongodb.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:484)
	at com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:236)
	at com.mongodb.connection.netty.NettyStream.handleReadResponse(NettyStream.java:266)
	at com.mongodb.connection.netty.NettyStream.access$600(NettyStream.java:66)
	at com.mongodb.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:325)
	at com.mongodb.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:322)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:482)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by kaiso** [comment]
Hello, it is the normal behavior, MongoDB ids can not be of type Long and must be compatible with their standard. So in RelMongo Identifier must either be of type String or type ObjectId.

**Comment by i-telligence-af** [comment]
Hi, sorry to post in a closed issue. I ran into the same problem and tried to produce a workaround, which failed due to other reasons. I think that MongoDB now supports Long (and other types) as the _id Field.

https://docs.spring.io/spring-data/mongodb/docs/1.3.3.RELEASE/reference/html/mapping-chapter.html

_**7.1.1 How the '_id' field is handled in the mapping layer**
MongoDB requires that you have an '_id' field for all documents. If you don't provide one the driver will assign a ObjectId with a generated value. The "_id" field can be of any type the, other than arrays, so long as it is unique._

I've forked 3.4.0-RC1 and adapted [io.github.kaiso.relmongo.util.ObjectIdReaderCallback](https://github.com/i-telligence-af/relmongo/blob/long_id/src/main/java/io/github/kaiso/relmongo/util/ObjectIdReaderCallback.java) to also support Long.

Do you think that is sensible? I guess other types should be supported as well?

I've also had to adapt the mapIdentifier method in [io.github.kaiso.relmongo.mongo.DocumentUtils](https://github.com/i-telligence-af/relmongo/blob/long_id/src/main/java/io/github/kaiso/relmongo/mongo/DocumentUtils.java) respectively.

**Comment by kaiso** [comment]
Hello,

Thank for you interest on RelMongo,
can you create a new issue please ? 
I will check that in the coming few days. 

Thank You,

**Comment by i-telligence-af** [comment]
Hey, sure

https://github.com/kaiso/relmongo/issues/59

Many thanks and happy weekend!

____________________________________

i-telligence.de <http://www.i-telligence.de/> gmbh

alex fuckert
georgenstraße 123
80797 münchen

mail	alexander.fuckert@i-telligence.de <mailto:alexander.fuckert@i-telligence.de>
tel	+49-(0)89-890 5566-66

ustid DE266803025

hrb 181321
amtsgericht münchen

geschäftsführung: armin ridzewski
