### ISSUE TITLE
No bean named 'mongoTemplate' available

### ISSUE THREAD

**Issue by atigm** [kaiso/relmongo#74]
I have a problem with some tests

I use

```
@RunWith(SpringRunner.class)
@WebMvcTest(UtilisateursRest.class)
@AutoConfigureMockMvc(addFilters = false)
class UsersRestTest {
```

The error :

```
Failed to load ApplicationContext
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:132)
...
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoTemplate$RelMongo$OK$RLMIndexCreator': Cannot resolve reference to bean 'mongoTemplate' while setting constructor argument; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'mongoTemplate' available
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342)
....
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'mongoTemplate' available
```

For other tests, its work fine : 
```
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = MOCK)
@TestMethodOrder(OrderAnnotation.class)
@AutoConfigureMockMvc
class UserRestIT {
```
and
```
@ExtendWith(MockitoExtension.class)
class UserServiceTest {
```

**Comment by atigm** [comment]
Its not working with @WebMvcTest(UtilisateursRest.class), I replace it by @SpringBootTest(webEnvironment = MOCK)
